---
- name: Ensure Logstash SSL key pair directory exists.
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory

- name: load secret server key
  include_vars: "serverkey.yml"
  # prevents logging of secrets
  no_log: true

- name: copy secret server key
  copy:
    dest: "{{ logstash_ssl_dir }}/{{ logstash_ssl_key_file }}"
    #logstash_ssl_key_file is the encrypted var created in the vars file
    content: "{{ logstash_ssl_key }}"
    #since logstash runs as logstash it can't read in root-owned 600 mode keys, so we chown to logstash :/
    owner: logstash
    group: root
    mode: 0600
  notify: restart logstash
  no_log: true

- name: Copy SSL key and cert for logstash-forwarder.
  copy:
    src: "{{ item }}"
    dest: "{{ logstash_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ logstash_ssl_certificate_file }}"
    - "{{ logstash_ssl_cafile }}"
  notify: restart logstash
